version: "3"

services:
  cluster_a_master:
    build: ./master
    environment:
      - POSTGRES_USER=postgres
      - PG_REP_USER=replication
      - PG_REP_PASSWORD=replication
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - pg_cluster

  cluster_a_slave_1:
    build: ./slave
    environment:
      - POSTGRES_USER=postgres
      - PG_REP_USER=replication
      - PG_REP_PASSWORD=replication
      - PG_REP_FROM=cluster_a_master
    ports:
      - 5432
    networks:
      default:
        aliases:
          - pg_cluster

  cluster_a_slave_2:
    build: ./slave
    environment:
      - POSTGRES_USER=postgres
      - PG_REP_USER=replication
      - PG_REP_PASSWORD=replication
      - PG_REP_FROM=cluster_a_master
    ports:
      - 5432
    networks:
      default:
        aliases:
          - pg_cluster

  cluster_b_master:
    build: ./master
    environment:
      - POSTGRES_USER=postgres
      - PG_REP_USER=replication
      - PG_REP_PASSWORD=replication
    ports:
      - 5432
    networks:
      default:
        aliases:
          - pg_cluster

  cluster_b_slave_1:
    build: ./slave
    environment:
      - POSTGRES_USER=postgres
      - PG_REP_USER=replication
      - PG_REP_PASSWORD=replication
      - PG_REP_FROM=cluster_b_master
    ports:
      - 5432
    networks:
      default:
        aliases:
          - pg_cluster

volumes:
  pg_data:
