version: "3"

services:
  master:
    build: ./master
    labels:
      com.finnerds.description: "Postgres master a with 'n' standby instances"
    environment:
      - POSTGRES_USER=postgres
      - PG_REP_USER=replication
      - PG_REP_PASSWORD=replication
    ports:
      - 5432:5432
    hostname: "master"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - pg_cluster

  standby:
    build: ./standby
    labels:
      com.finnerds.description: "Postgres standby 'n'"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - PG_REP_USER=replication
      - PG_REP_PASSWORD=replication
      - PG_REP_FROM=master
    ports:
      - 5432
    networks:
      default:
        aliases:
          - pg_cluster
    depends_on:
      - master

volumes:
  pg_data:
