version: "3"

services:
  master:
    image: 'finnerds/postgres_a:latest'
    environment:
      - POSTGRES_USER=postgres
      - PG_REP_USER=replication
      - PG_REP_PASSWORD=replication
    ports:
      - 5432:5432
    hostname: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      default:
        aliases:
          - pg_cluster
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - 'postgresql_master_data:/var/lib/postgresql/data'      

  standby:
    image: 'finnerds/postgres_b:latest'
    labels:
      com.finnerds.description: "Postgres standby 'n'"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - PG_REP_USER=replication
      - PG_REP_PASSWORD=replication
      - PG_REP_FROM=db
    ports:
      - 5432
    depends_on:
      - master_a
    deploy:
      replicas: 3
      placement:
        constraints: [node.role != manager]
    networks:
      default:
        aliases:
          - pg_cluster
    volumes:
      - 'postgresql_standby_data:/var/lib/postgresql/data'     

volumes:
  postgresql_master_data:
    driver: local
  postgresql_standby_data:
    driver: local
